services:
  - postgresql
before_script:
  - psql -c 'create database if not exists teamwork;' -U postgres
language: node_js
node_js:
  - 10.14.1
branches:
  only:
    - develop
install:
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm test
